"""add announcements table

Revision ID: 9792f03a6591
Revises: 11bb942d01cf
Create Date: 2026-04-30 01:30:41.914918

"""
from typing import Sequence, Union

from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9792f03a6591'
down_revision: Union[str, Sequence[str], None] = '11bb942d01cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachment_type', sa.String(length=20), nullable=True),
    sa.Column('attachment_title', sa.String(length=255), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('link_url', sa.String(length=2000), nullable=True),
    sa.Column('youtube_url', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_classroom_id'), 'announcements', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_announcements_created_by_id'), 'announcements', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_announcements_file_id'), 'announcements', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_announcements_file_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_created_by_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_classroom_id'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
